import { ExecutionDecisionProviderFailure } from "../../governance/execution-decision-provider.js";
import { createProductionExecutionDecisionService } from "../../governance/execution-decision-production.js";
import type { ProviderKeychainReader } from "../keychain-reader.js";
import type { DesktopExecutionDecisionResult } from "./execution-decision-contract.js";
import { createCliExecutionDecisionProposer, ExecutionDecisionCliBoundaryFailure } from "./execution-decision-cli-proposer.js";
import type { CliInvoker } from "../cli-invoker.js";
import { ExecutionDecisionApprovalStageFailure, ExecutionDecisionDraftValidationFailure, ExecutionDecisionPreparationStageFailure } from "../../governance/execution-decision-errors.js";
import { createCliExecutionDecisionCurrent, ExecutionDecisionCurrentCliFailure } from "./execution-decision-cli-current.js";
import type { ExecutionDecisionCurrent } from "../../governance/execution-decision-service.js";

const messages: Readonly<Record<string, string>> = {
  decision_draft_invalid: "Le brouillon de décision est invalide.", decision_draft_missing: "Ce brouillon n’est plus disponible.",
  decision_draft_stale: "Le contexte a changé. Préparez une nouvelle décision.", decision_draft_serialize_failed: "La décision n’a pas pu être sérialisée.", decision_draft_write_failed: "L’écriture de la décision a échoué.", decision_draft_read_previous_failed: "La décision actuelle n’a pas pu être lue avant remplacement.", decision_draft_write_temp_failed: "Le fichier temporaire de décision n’a pas pu être écrit.", decision_draft_rename_failed: "La décision préparée n’a pas pu remplacer la décision actuelle.",
  decision_draft_post_write_invalid: "La décision écrite n’a pas pu être validée.", decision_draft_recovery_failed: "La récupération de sécurité a échoué.", decision_draft_commit_failed: "La finalisation de la décision a échoué.", execution_decision_approval_current_failed: "Loop Engine n’a pas pu relire l’état courant avant l’approbation.", execution_decision_approval_publish_failed: "Loop Engine n’a pas pu publier la décision.", execution_decision_approval_validate_failed: "Loop Engine n’a pas pu valider la décision publiée.", execution_decision_approval_recover_failed: "Loop Engine n’a pas pu récupérer la décision publiée.", execution_decision_approval_commit_failed: "Loop Engine n’a pas pu finaliser l’approbation de la décision.", execution_decision_approval_internal_error: "Loop Engine a rencontré une erreur interne pendant l’approbation de la décision.",
  provider_authentication_failed: "Authentification Anthropic refusée.", provider_permission_denied: "La clé Anthropic n’a pas accès à cette ressource.", provider_rate_limited: "Limite Anthropic atteinte.", provider_timeout: "Anthropic n’a pas répondu dans le délai prévu.", provider_request_failed: "La requête envoyée à Anthropic a été refusée.", provider_billing_failed: "La facturation Anthropic ne permet pas cette requête.", provider_not_found: "La ressource Anthropic demandée est introuvable.", provider_request_too_large: "La requête envoyée à Anthropic est trop volumineuse.", provider_response_invalid: "La réponse Anthropic est invalide.", provider_refused: "Anthropic a refusé cette demande.", provider_output_truncated: "La réponse Anthropic a été tronquée.", provider_server_error: "Le service Anthropic est temporairement indisponible.", provider_unavailable: "Le service Anthropic est temporairement indisponible.", repository_unavailable: "Le dépôt Loop Engine n’est pas disponible.", cli_spawn_failed: "Le processus de proposition n’a pas pu être lancé.", cli_timeout: "Le processus de proposition a dépassé le délai prévu.", cli_response_invalid: "Loop Engine n’a pas pu interpréter la réponse du processus de proposition.", execution_decision_current_failed: "Loop Engine n’a pas pu lire l’état courant de la décision.", execution_decision_current_spawn_failed: "Le processus de lecture de la décision n’a pas pu être lancé.", execution_decision_current_timeout: "Le processus de lecture de la décision a dépassé le délai prévu.", execution_decision_current_response_invalid: "Loop Engine n’a pas pu interpréter l’état courant de la décision.", execution_decision_propose_failed: "Loop Engine a rencontré une erreur interne pendant la préparation de la décision.", execution_decision_draft_failed: "Loop Engine a rencontré une erreur interne pendant la préparation de la décision.", execution_decision_internal_error: "Loop Engine a rencontré une erreur interne pendant la préparation de la décision.",
};
const failed = (code: string, message?: string, provider?: Extract<DesktopExecutionDecisionResult, { ok: false }> ["provider"]): DesktopExecutionDecisionResult => ({ ok: false, code, message: message ?? messages[code] ?? "La préparation de la décision est indisponible.", ...(provider === undefined ? {} : { provider }) });
const draftMessage = (issue: ExecutionDecisionDraftValidationFailure["draftValidationIssue"]) => issue === "allowed_paths_invalid" || issue === "protected_path" ? "Le périmètre de fichiers proposé est invalide." : issue === "forbidden_terms_invalid" ? "Les contraintes de contenu proposées sont invalides." : "Les champs proposés sont invalides.";

export function createDesktopExecutionDecisionController(options: Readonly<{ keychainReader: ProviderKeychainReader; cliInvoker: CliInvoker; currentCliInvoker?: CliInvoker; resolveRepositoryPath: () => string | null; current?: (projectName: string) => Promise<ExecutionDecisionCurrent | null>; service?: Pick<ReturnType<typeof createProductionExecutionDecisionService>, "prepare" | "approve"> }>) {
  const current = options.current ?? createCliExecutionDecisionCurrent({ cliInvoker: options.currentCliInvoker ?? options.cliInvoker, resolveRepositoryPath: options.resolveRepositoryPath });
  const service = options.service ?? createProductionExecutionDecisionService(createCliExecutionDecisionProposer(options), { current });
  return Object.freeze({
    async prepare(projectName: unknown): Promise<DesktopExecutionDecisionResult> {
      try { const result = await service.prepare(projectName); if (!result.ok) return failed(result.code); return result; }
      catch (error) { if (error instanceof ExecutionDecisionDraftValidationFailure) return failed("decision_draft_invalid", draftMessage(error.draftValidationIssue), { model: error.telemetry.model, durationMs: error.telemetry.durationMs, ...(error.telemetry.usage === undefined ? {} : { usage: error.telemetry.usage }), ...(error.telemetry.actualCalculatedCostUsd === undefined ? {} : { actualCalculatedCostUsd: error.telemetry.actualCalculatedCostUsd }), ...(error.telemetry.pricingEffectiveDate === undefined ? {} : { pricingEffectiveDate: error.telemetry.pricingEffectiveDate }), draftValidationIssue: error.draftValidationIssue }); if (error instanceof ExecutionDecisionProviderFailure) { const failure = error.failure; return failed(failure.code, undefined, { ...(failure.model === null ? {} : { model: failure.model }), durationMs: failure.durationMs, ...(failure.httpStatus === undefined ? {} : { httpStatus: failure.httpStatus }), failureCode: failure.code }); } if (error instanceof ExecutionDecisionPreparationStageFailure) { if (process.env.NODE_ENV !== "production") console.error(`[execution-decision] prepare failed stage=${error.stage} code=${error.code}`); return failed(error.code); } return failed(error instanceof ExecutionDecisionCliBoundaryFailure || error instanceof ExecutionDecisionCurrentCliFailure ? error.code : error instanceof Error && error.message === "keychain_unavailable" ? "keychain_unavailable" : error instanceof Error && error.message === "decision_draft_stale" ? "decision_draft_stale" : "execution_decision_internal_error", error instanceof Error && error.message === "keychain_unavailable" ? "Identifiant Anthropic indisponible dans le trousseau macOS." : undefined); }
    },
    async approve(draftId: unknown): Promise<DesktopExecutionDecisionResult> {
      try { const result = await service.approve(draftId); return result.ok ? { ok: true } : failed(result.code); }
      catch (error) { if (error instanceof ExecutionDecisionCurrentCliFailure || error instanceof ExecutionDecisionApprovalStageFailure) { if (process.env.NODE_ENV !== "production" && error instanceof ExecutionDecisionApprovalStageFailure) console.error(`[execution-decision] approve failed stage=${error.stage} code=${error.code}`); return failed(error.code); } return failed("execution_decision_approval_internal_error"); }
    },
  });
}
