import type { AnthropicEffort, RoadmapProposalProfile, RoadmapProposalUsage } from "./roadmap-proposal-contract.js";
export type GateReassessmentReport = Readonly<{ schemaVersion: 1; project: Readonly<{ name: string }>; profile?: RoadmapProposalProfile; result: Readonly<{ status: "unavailable"; reason: string } | { status: "failed"; reason: string; provider?: string; model?: string; effort?: AnthropicEffort | null; durationMs?: number; usage?: RoadmapProposalUsage; actualCalculatedCostUsd?: number } | { status: "completed"; provider: string; model: string; effort: AnthropicEffort | null; durationMs: number; usage?: RoadmapProposalUsage; actualCalculatedCostUsd?: number }>; assessment?: Readonly<{ status: "no_new_signal"; reason: string } | { status: "review_recommended"; reason: string; gates: readonly Readonly<{ phase: string; blockedBy: string; observedSignal: string; recommendation: string }>[] }>; }>;
const object = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v);
export function parseGateReassessmentReport(v: unknown): GateReassessmentReport | null {
  if (!object(v) || v.schemaVersion !== 1 || !object(v.project) || typeof v.project.name !== "string" || !object(v.result) || typeof v.result.status !== "string") return null;
  const result = v.result; if (result.status === "unavailable" && typeof result.reason === "string") return { schemaVersion: 1, project: { name: v.project.name }, result: { status: "unavailable", reason: result.reason } };
  if (result.status !== "completed" || typeof result.provider !== "string" || typeof result.model !== "string" || typeof result.durationMs !== "number" || (result.effort !== null && typeof result.effort !== "string") || !object(v.assessment) || typeof v.assessment.reason !== "string") return null;
  const assessment = v.assessment.status === "no_new_signal" ? { status: "no_new_signal" as const, reason: v.assessment.reason } : v.assessment.status === "review_recommended" && Array.isArray(v.assessment.gates) && v.assessment.gates.length <= 3 && v.assessment.gates.every((g) => object(g) && typeof g.phase === "string" && typeof g.blockedBy === "string" && typeof g.observedSignal === "string" && typeof g.recommendation === "string") ? { status: "review_recommended" as const, reason: v.assessment.reason, gates: v.assessment.gates as readonly Readonly<{ phase: string; blockedBy: string; observedSignal: string; recommendation: string }>[] } : null;
  const usage = object(result.usage) && typeof result.usage.inputTokens === "number" && typeof result.usage.outputTokens === "number" ? { inputTokens: result.usage.inputTokens, outputTokens: result.usage.outputTokens } : undefined;
  return assessment === null ? null : { schemaVersion: 1, project: { name: v.project.name }, ...(v.profile === "economy" || v.profile === "balanced" || v.profile === "deep" ? { profile: v.profile } : {}), result: { status: "completed", provider: result.provider, model: result.model, effort: result.effort as AnthropicEffort | null, durationMs: result.durationMs, ...(usage ? { usage } : {}), ...(typeof result.actualCalculatedCostUsd === "number" ? { actualCalculatedCostUsd: result.actualCalculatedCostUsd } : {}) }, assessment };
}
