import { resolveRoadmapProposalProfile } from "../intelligence/roadmap-proposal-routing.js";
import type { TextOnlyProvider, TextOnlyProviderFailure } from "../text-only-provider/index.js";
import type { ExecutionDecisionCurrent, ExecutionDecisionProviderProposal } from "./execution-decision-service.js";
import { loadConfig } from "../core/config.js";
import { findProject } from "../core/project.js";
import { generateProjectReport } from "../core/reports.js";
import { ExecutionDecisionPreparationPassthroughFailure } from "./execution-decision-errors.js";
import { readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

export const EXECUTION_DECISION_PROPOSAL_SCHEMA = Object.freeze({ type: "object", additionalProperties: false, required: ["objective", "deliverables", "outOfScope", "allowedPaths"], properties: { objective: { type: "string" }, deliverables: { type: "array", items: { type: "string" } }, outOfScope: { type: "array", items: { type: "string" } }, allowedPaths: { type: "array", items: { type: "string" } }, forbiddenContentTerms: { type: "array", items: { type: "string" } } } });
const SYSTEM = "Propose only a decision draft. You cannot authorize READY. Use only supplied JSON. Return JSON only. Allowed paths MUST be exact repository-relative POSIX file paths, or a terminal /** scope only when multiple files are genuinely required. NEVER return paths ending with /, bare directories, .git, .governance, the execution decision file, or broad parent directories when exact files can be named. The candidate.source document is the canonical planning source: allowedPaths MUST include candidate.source exactly so the execution can update the candidate state after completing the deliverable. Include that planning-source update in deliverables. Use repositoryPathHints to follow the project's existing file layout. Do not invent an alternative directory when an established convention exists. For a new ADR, infer the next filename from existing ADR files. Prefer the exact new artifact path plus candidate.source; add other paths only when genuinely required. Example: existing ADR/0005-example.md and ADR/0006-example.md means a new ADR should be ADR/0007-meaningful-slug.md. No tools, shell, web, Git, or filesystem.";
export class ExecutionDecisionProviderFailure extends ExecutionDecisionPreparationPassthroughFailure { readonly failure: TextOnlyProviderFailure; constructor(failure: TextOnlyProviderFailure) { super(); this.message = "Execution decision provider failed."; this.name = "ExecutionDecisionProviderFailure"; this.failure = failure; } }
function isStringArray(value: unknown): value is readonly string[] { return Array.isArray(value) && value.every((item) => typeof item === "string"); }
function parse(value: unknown): ExecutionDecisionProviderProposal | null { if(typeof value!=="object"||value===null||Array.isArray(value))return null;const v=value as Record<string,unknown>;if(Object.keys(v).some(k=>!["objective","deliverables","outOfScope","allowedPaths","forbiddenContentTerms"].includes(k))||typeof v.objective!=="string"||!isStringArray(v.deliverables)||!isStringArray(v.outOfScope)||!isStringArray(v.allowedPaths)||(v.forbiddenContentTerms!==undefined&&!isStringArray(v.forbiddenContentTerms)))return null;return Object.freeze({ objective: v.objective, deliverables: v.deliverables, outOfScope: v.outOfScope, allowedPaths: v.allowedPaths, ...(v.forbiddenContentTerms === undefined || v.forbiddenContentTerms.length === 0 ? {} : { forbiddenContentTerms: v.forbiddenContentTerms }) }); }
const MAX_DOCUMENTATION_PATH_HINTS = 60;
const MAX_DOCUMENTATION_PATH_DEPTH = 3;
function hintPath(root: string, path: string): string | null { const candidate = relative(root, path).split(sep).join("/"); if (!candidate.endsWith(".md") || candidate.length === 0 || candidate.startsWith("../") || candidate.split("/").length > MAX_DOCUMENTATION_PATH_DEPTH || candidate.split("/").some((part) => part.length === 0 || part.startsWith(".") || part === "node_modules")) return null; return candidate; }
function collectDocumentationPaths(root: string, directory: string): readonly string[] { const collected: string[] = []; const visit = (path: string) => { let entries; try { entries = readdirSync(path, { withFileTypes: true }); } catch { return; } for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) { if (entry.name.startsWith(".") || entry.name === "node_modules") continue; const child = join(path, entry.name); const candidate = hintPath(root, child); if (entry.isFile() && candidate !== null) collected.push(candidate); else if (entry.isDirectory() && candidate === null && (relative(root, child).split(sep).filter(Boolean).length < MAX_DOCUMENTATION_PATH_DEPTH)) visit(child); } }; visit(directory); return collected; }
export function buildRepositoryPathHints(projectPath: string, sourceDocument: string): Readonly<{ existingDocumentationPaths: readonly string[] }> { const sourceDirectory = sourceDocument.includes("/") ? sourceDocument.slice(0, sourceDocument.lastIndexOf("/")) : ""; const paths = new Set<string>(); for (const directory of [sourceDirectory, "ADR", "docs"]) { if (directory.startsWith(".") || directory === "") continue; for (const path of collectDocumentationPaths(projectPath, join(projectPath, directory))) paths.add(path); } for (const name of ["README.md", "AGENTS.md"]) { try { if (statSync(join(projectPath, name)).isFile()) paths.add(name); } catch { /* absent documentation is not an error */ } } const priority = (path: string) => path === sourceDocument ? 0 : sourceDirectory !== "" && path.startsWith(`${sourceDirectory}/`) ? 1 : path.startsWith("ADR/") ? 2 : path.startsWith("docs/") ? 3 : 4; return Object.freeze({ existingDocumentationPaths: Object.freeze([...paths].sort((a, b) => priority(a) - priority(b) || a.localeCompare(b)).slice(0, MAX_DOCUMENTATION_PATH_HINTS)) }); }
export type ExecutionDecisionProviderCompleted = Readonly<{ status: "completed"; provider: string; model: string; effort: "low"; durationMs: number; usage?: Readonly<{ inputTokens: number; outputTokens: number }>; proposal: ExecutionDecisionProviderProposal }>;
export async function proposeExecutionDecisionWithTelemetry(provider: TextOnlyProvider, current: ExecutionDecisionCurrent, dependencies: Readonly<{ loadConfig?: typeof loadConfig; findProject?: typeof findProject; report?: typeof generateProjectReport }> = {}): Promise<ExecutionDecisionProviderCompleted> {
  const profile = resolveRoadmapProposalProfile("balanced");
  const project=(dependencies.findProject??findProject)((dependencies.loadConfig??loadConfig)(),current.project);const snapshot=project?(dependencies.report??generateProjectReport)(project):null;const candidate=snapshot?.roadmap.selectedCandidate;
  if(!project||!snapshot||!candidate?.id||candidate.id!==current.candidateId||candidate.path!==current.sourceDocument)throw new Error("Execution decision context is stale.");
  const context={project:{name:project.name,type:project.type,objective:snapshot.objective.content??null},planning:{mode:snapshot.planning.mode},candidate:{id:candidate.id,text:candidate.text,source:candidate.path},roadmap:{summary:snapshot.roadmap.summary},repositoryPathHints:buildRepositoryPathHints(current.projectPath, current.sourceDocument)};
  const result = await provider.invoke({ systemPrompt: SYSTEM, contextJson: JSON.stringify(context), model: profile.model, effort: "low", timeoutMs: 60_000, outputSchema: { schema: EXECUTION_DECISION_PROPOSAL_SCHEMA } });
  if (result.status !== "completed") throw new ExecutionDecisionProviderFailure(result);
  let output: unknown; try { output = JSON.parse(result.output); } catch { throw new Error("Execution decision proposal is invalid."); }
  const proposal=parse(output);if(!proposal)throw new Error("Execution decision proposal is invalid.");
  return Object.freeze({ status: "completed", provider: result.provider, model: result.model, effort: "low", durationMs: result.durationMs, ...(result.usage === undefined ? {} : { usage: result.usage }), proposal });
}
export function createExecutionDecisionProposalProvider(provider: TextOnlyProvider, dependencies: Readonly<{ loadConfig?: typeof loadConfig; findProject?: typeof findProject; report?: typeof generateProjectReport }> = {}): (current: ExecutionDecisionCurrent) => Promise<ExecutionDecisionProviderProposal> {
  return async (current) => (await proposeExecutionDecisionWithTelemetry(provider, current, dependencies)).proposal;
}
