import { resolveRoadmapProposalProfile } from "../intelligence/roadmap-proposal-routing.js";
import type { TextOnlyProvider } from "../text-only-provider/index.js";
import type { ExecutionDecisionCurrent, ExecutionDecisionProviderProposal } from "./execution-decision-service.js";
import { loadConfig } from "../core/config.js";
import { findProject } from "../core/project.js";
import { generateProjectReport } from "../core/reports.js";

export const EXECUTION_DECISION_PROPOSAL_SCHEMA = Object.freeze({ type: "object", additionalProperties: false, required: ["objective", "deliverables", "outOfScope", "allowedPaths"], properties: { objective: { type: "string" }, deliverables: { type: "array", items: { type: "string" } }, outOfScope: { type: "array", items: { type: "string" } }, allowedPaths: { type: "array", items: { type: "string" } }, forbiddenContentTerms: { type: "array", items: { type: "string" } } } });
const SYSTEM = "Propose only a decision draft. You cannot authorize READY. Use only supplied JSON. Return JSON only. Propose minimal paths; never .git or the execution decision file. No tools, shell, web, Git, or filesystem.";
function isStringArray(value: unknown): value is readonly string[] { return Array.isArray(value) && value.every((item) => typeof item === "string"); }
function parse(value: unknown): ExecutionDecisionProviderProposal | null { if(typeof value!=="object"||value===null||Array.isArray(value))return null;const v=value as Record<string,unknown>;if(Object.keys(v).some(k=>!["objective","deliverables","outOfScope","allowedPaths","forbiddenContentTerms"].includes(k))||typeof v.objective!=="string"||!isStringArray(v.deliverables)||!isStringArray(v.outOfScope)||!isStringArray(v.allowedPaths)||(v.forbiddenContentTerms!==undefined&&!isStringArray(v.forbiddenContentTerms)))return null;return v as ExecutionDecisionProviderProposal; }
export function createExecutionDecisionProposalProvider(provider: TextOnlyProvider, dependencies: Readonly<{ loadConfig?: typeof loadConfig; findProject?: typeof findProject; report?: typeof generateProjectReport }> = {}): (current: ExecutionDecisionCurrent) => Promise<ExecutionDecisionProviderProposal> {
  const profile = resolveRoadmapProposalProfile("balanced");
  return async (current) => { const project=(dependencies.findProject??findProject)((dependencies.loadConfig??loadConfig)(),current.project);const snapshot=project?(dependencies.report??generateProjectReport)(project):null;const candidate=snapshot?.roadmap.selectedCandidate;if(!project||!snapshot||!candidate?.id||candidate.id!==current.candidateId||candidate.path!==current.sourceDocument)throw new Error("Execution decision context is stale."); const context={project:{name:project.name,type:project.type,objective:snapshot.objective.content??null},planning:{mode:snapshot.planning.mode},candidate:{id:candidate.id,text:candidate.text,source:candidate.path},roadmap:{summary:snapshot.roadmap.summary}}; const result = await provider.invoke({ systemPrompt: SYSTEM, contextJson: JSON.stringify(context), model: profile.model, ...(profile.effort === null ? {} : { effort: profile.effort }), timeoutMs: 60_000, outputSchema: { schema: EXECUTION_DECISION_PROPOSAL_SCHEMA } }); if (result.status !== "completed") throw new Error("Execution decision proposal unavailable."); let output: unknown; try { output = JSON.parse(result.output); } catch { throw new Error("Execution decision proposal is invalid."); } const parsed=parse(output);if(!parsed)throw new Error("Execution decision proposal is invalid.");return parsed; };
}
