import assert from "node:assert/strict";
import { describe, test } from "node:test";
import { createAuthorityLifecycle } from "../../src/authority/lifecycle/index.js";
import type { AuthorityLifecycleContext, AuthorityLifecycleEvent, AuthorityLifecycleSubject } from "../../src/authority/lifecycle/index.js";
const subject: AuthorityLifecycleSubject = { type: "execution_authority", id: "authority.a", version: "v1", authorityId: "authority.a", approvalId: "approval.a", policyId: "policy.a", providerId: "provider.a", protocolId: "protocol.a", mappingId: "mapping.a", intentId: "intent.a" };
const context: AuthorityLifecycleContext = { evaluationAt: "2026-07-18T12:00:00.000Z", expectedSubjectId: "authority.a", expectedSubjectVersion: "v1", expectedPolicyId: "policy.a", supportedSubjectTypes: ["execution_authority", "operator_approval"], supportedEventTypes: ["issued", "activated", "expiry_scheduled", "expired", "revocation_requested", "revoked", "superseded", "replacement_declared", "reviewed", "corrected"] };
function event(type: AuthorityLifecycleEvent["type"], at = "2026-07-18T10:00:00.000Z", overrides: Partial<AuthorityLifecycleEvent> = {}): AuthorityLifecycleEvent { return { id: `${type}.${at}`, type, subject, issuer: { id: "issuer.a", type: "operator" }, occurredAt: at, effectiveAt: at, reason: { code: type, detail: "declared" }, evidenceReferences: ["evidence.a"], review: { reviewerId: "reviewer.a", reviewedAt: at, status: "complete", references: ["review.a"] }, scope: "exact_version", correlationId: "replacement.a:v2", ...overrides }; }
describe("revocation and expiry lifecycle RFC", () => {
  test("is deterministic, immutable, active, and default-denied", () => { const result = createAuthorityLifecycle(subject, [event("issued")], context); assert.equal(result.state, "active"); assert.equal(result.active, true); assert.equal(result.executionAllowed, false); assert.equal(result.executionStarted, false); assert.equal(Object.isFrozen(result), true); assert.equal(Object.isFrozen(result.lifecycle.events), true); });
  test("applies time and terminal precedence without implicit restoration", () => { assert.equal(createAuthorityLifecycle(subject, [event("issued", "2026-07-18T13:00:00.000Z")], context).state, "not_yet_valid"); assert.equal(createAuthorityLifecycle(subject, [event("issued"), event("expiry_scheduled", "2026-07-18T12:00:00.000Z")], context).state, "expired"); assert.equal(createAuthorityLifecycle(subject, [event("issued"), event("expiry_scheduled"), event("revoked")], context).state, "revoked"); assert.equal(createAuthorityLifecycle(subject, [event("issued"), event("superseded")], context).state, "superseded"); });
  test("fails closed for missing or inconsistent lifecycle data", () => { assert.equal(createAuthorityLifecycle(null, [], context).state, "invalid"); assert.equal(createAuthorityLifecycle(subject, [event("issued"), event("issued")], context).state, "invalid"); assert.equal(createAuthorityLifecycle(subject, [event("issued", "invalid")], context).state, "invalid"); assert.equal(createAuthorityLifecycle(subject, [event("replacement_declared", undefined, { correlationId: "authority.a:v1" })], context).state, "invalid"); });
});
