import {
  AUDIT_CATEGORY_SUMMARY_RULE,
  AUDIT_CI_SCRIPT_RULE,
  AUDIT_GLOBAL_STATUS_RULE,
  AUDIT_GITHUB_ACTIONS_CI_RULE,
  AUDIT_PRIORITY_EXPOSURE_RULE,
  AUDIT_PRIORITY_SUMMARY_RULE,
  AUDIT_RECOMMENDATION_REPORT_RULE,
  AUDIT_RECOMMENDATION_SUMMARY_RULE,
  AUDIT_RECOMMENDATION_SUPPORT_RULE,
  AUDIT_SCORE_EXPOSURE_RULE,
  AUDIT_STRICT_MODE_RULE,
  AUDIT_STRICT_SCRIPT_RULE,
} from "./rules/audit.js";
import { CLI_COMMAND_COVERAGE_RULE } from "./rules/cli.js";
import { AUDIT_DOCUMENTATION_COVERAGE_RULE } from "./rules/docs.js";
import {
  AUDIT_JSON_SUMMARY_CONTRACT_RULE,
  JSON_CHECK_COVERAGE_RULE,
  JSON_SCHEMA_VERSION_RULE,
} from "./rules/json.js";
import type { AuditRule } from "./types.js";


export const AUDIT_RULES: readonly AuditRule[] = [
  JSON_SCHEMA_VERSION_RULE,
  JSON_CHECK_COVERAGE_RULE,
  AUDIT_JSON_SUMMARY_CONTRACT_RULE,
  CLI_COMMAND_COVERAGE_RULE,
  AUDIT_DOCUMENTATION_COVERAGE_RULE,
  AUDIT_SCORE_EXPOSURE_RULE,
  AUDIT_PRIORITY_EXPOSURE_RULE,
  AUDIT_RECOMMENDATION_SUPPORT_RULE,
  AUDIT_CATEGORY_SUMMARY_RULE,
  AUDIT_RECOMMENDATION_REPORT_RULE,
  AUDIT_PRIORITY_SUMMARY_RULE,
  AUDIT_RECOMMENDATION_SUMMARY_RULE,
  AUDIT_GLOBAL_STATUS_RULE,
  AUDIT_STRICT_MODE_RULE,
  AUDIT_STRICT_SCRIPT_RULE,
  AUDIT_CI_SCRIPT_RULE,
  AUDIT_GITHUB_ACTIONS_CI_RULE,
];
