import { createAuditRuleRegistry } from "./registry.js";
import { RUNTIME_EXECUTION_PUBLIC_RESULT_FACADE_RULE } from "./rules/runtime-execution-public-result-facade.js";
import { RUNTIME_EXECUTION_RECEIPT_REPORTING_RULE } from "./rules/runtime-execution-receipt-reporting.js";
import { RUNTIME_EXECUTION_RECEIPT_REPORTING_SERIALIZATION_RULE } from "./rules/runtime-execution-receipt-reporting-serialization.js";
import { RUNTIME_RULE_INVENTORY_NORMALIZATION_RULE } from "./rules/runtime-rule-inventory-normalization.js";
import {
  RUNTIME_AUDIT_MANIFEST_CONSISTENCY_RULE,
  registerRuntimeAuditManifestInventory,
} from "./rules/runtime-audit-manifest-consistency.js";
import { INBOUND_SECURITY_CONTRACT_RULE } from "./rules/inbound-security-contract.js";
import { INBOUND_SECURITY_GATE_RULE } from "./rules/inbound-security-gate.js";
import { INBOUND_AUTHENTICATION_VERIFICATION_RULE } from "./rules/inbound-authentication-verification.js";
import { INBOUND_AUTHENTICATION_GATE_RULE } from "./rules/inbound-authentication-gate.js";
import { INBOUND_REQUEST_HANDLER_NEUTRALITY_RULE } from "./rules/inbound-request-handler-neutrality.js";
import { INBOUND_REQUEST_HANDLER_GATE_RULE } from "./rules/inbound-request-handler-gate.js";
import { INBOUND_TRANSPORT_ADAPTER_NEUTRALITY_RULE } from "./rules/inbound-transport-adapter-neutrality.js";
import { INBOUND_TRANSPORT_ADAPTER_GATE_RULE } from "./rules/inbound-transport-adapter-gate.js";
import { INBOUND_REPLAY_PROTECTION_NEUTRALITY_RULE } from "./rules/inbound-replay-protection-neutrality.js";
import { INBOUND_REPLAY_PROTECTION_GATE_RULE } from "./rules/inbound-replay-protection-gate.js";
import { INBOUND_REPLAY_PROTECTED_AUTHENTICATION_NEUTRALITY_RULE } from "./rules/inbound-replay-protected-authentication-neutrality.js";
import { INBOUND_REPLAY_PROTECTED_AUTHENTICATION_GATE_RULE } from "./rules/inbound-replay-protected-authentication-gate.js";
import { INBOUND_EVALUATION_TIME_COHERENCE_RULE } from "./rules/inbound-evaluation-time-coherence.js";
import { INBOUND_EVALUATION_TIME_COHERENCE_GATE_RULE } from "./rules/inbound-evaluation-time-coherence-gate.js";
import { INBOUND_REPLAY_EVIDENCE_BINDING_RULE } from "./rules/inbound-replay-evidence-binding.js";
import { INBOUND_REPLAY_EVIDENCE_BINDING_GATE_RULE } from "./rules/inbound-replay-evidence-binding-gate.js";
import { INBOUND_PRINCIPAL_BINDING_RULE } from "./rules/inbound-principal-binding.js";
import { INBOUND_PRINCIPAL_BINDING_GATE_RULE } from "./rules/inbound-principal-binding-gate.js";
import { INBOUND_PRINCIPAL_PRESENCE_RULE } from "./rules/inbound-principal-presence.js";
import { INBOUND_PRINCIPAL_PRESENCE_GATE_RULE } from "./rules/inbound-principal-presence-gate.js";
import { INBOUND_AUTH_EVIDENCE_VALIDITY_RULE } from "./rules/inbound-auth-evidence-validity.js";
import { INBOUND_AUTH_EVIDENCE_VALIDITY_GATE_RULE } from "./rules/inbound-auth-evidence-validity-gate.js";
import { INBOUND_TENANT_BINDING_RULE } from "./rules/inbound-tenant-binding.js";
import { INBOUND_TENANT_BINDING_GATE_RULE } from "./rules/inbound-tenant-binding-gate.js";
import { INBOUND_OPERATION_BINDING_RULE } from "./rules/inbound-operation-binding.js";
import { INBOUND_OPERATION_BINDING_GATE_RULE } from "./rules/inbound-operation-binding-gate.js";
import { INBOUND_OPERATION_POLICY_ADMISSION_RULE } from "./rules/inbound-operation-policy-admission.js";
import { INBOUND_OPERATION_POLICY_ADMISSION_GATE_RULE } from "./rules/inbound-operation-policy-admission-gate.js";
import { INBOUND_REPLAY_REQUEST_BINDING_RULE } from "./rules/inbound-replay-request-binding.js";
import { INBOUND_REPLAY_REQUEST_BINDING_GATE_RULE } from "./rules/inbound-replay-request-binding-gate.js";
import { INBOUND_REPLAY_STATE_REJECTION_RULE } from "./rules/inbound-replay-state-rejection.js";
import { INBOUND_REPLAY_STATE_REJECTION_GATE_RULE } from "./rules/inbound-replay-state-rejection-gate.js";
import { INBOUND_PROJECT_BINDING_RULE } from "./rules/inbound-project-binding.js";
import { INBOUND_PROJECT_BINDING_GATE_RULE } from "./rules/inbound-project-binding-gate.js";
import { INBOUND_REPLAY_RECEIPT_TIME_VALIDATION_RULE } from "./rules/inbound-replay-receipt-time-validation.js";
import { INBOUND_REPLAY_RECEIPT_TIME_VALIDATION_GATE_RULE } from "./rules/inbound-replay-receipt-time-validation-gate.js";
import { INBOUND_REPLAY_PORT_RECEIPT_TIME_VALIDATION_RULE } from "./rules/inbound-replay-port-receipt-time-validation.js";
import { INBOUND_REPLAY_PORT_RECEIPT_TIME_VALIDATION_GATE_RULE } from "./rules/inbound-replay-port-receipt-time-validation-gate.js";
import { INBOUND_VERIFICATION_REQUEST_BINDING_RULE } from "./rules/inbound-verification-request-binding.js";
import { INBOUND_VERIFICATION_REQUEST_BINDING_GATE_RULE } from "./rules/inbound-verification-request-binding-gate.js";
import { INBOUND_VERIFICATION_EVALUATION_TIME_BINDING_RULE } from "./rules/inbound-verification-evaluation-time-binding.js";
import { INBOUND_VERIFICATION_EVALUATION_TIME_BINDING_GATE_RULE } from "./rules/inbound-verification-evaluation-time-binding-gate.js";
import { INBOUND_REPLAY_NONCE_VALIDATION_RULE } from "./rules/inbound-replay-nonce-validation.js";
import { INBOUND_REPLAY_NONCE_VALIDATION_GATE_RULE } from "./rules/inbound-replay-nonce-validation-gate.js";
import { INBOUND_AUTHENTICATION_EVIDENCE_WINDOW_VALIDATION_RULE } from "./rules/inbound-authentication-evidence-window-validation.js";
import { INBOUND_AUTHENTICATION_EVIDENCE_WINDOW_VALIDATION_GATE_RULE } from "./rules/inbound-authentication-evidence-window-validation-gate.js";
import { INBOUND_REPLAY_RECEIVED_AT_VALIDATION_RULE } from "./rules/inbound-replay-received-at-validation.js";
import { INBOUND_REPLAY_RECEIVED_AT_VALIDATION_GATE_RULE } from "./rules/inbound-replay-received-at-validation-gate.js";
import { INBOUND_EVALUATION_TIME_VALIDATION_RULE } from "./rules/inbound-evaluation-time-validation.js";
import { INBOUND_EVALUATION_TIME_VALIDATION_GATE_RULE } from "./rules/inbound-evaluation-time-validation-gate.js";
import { INBOUND_REQUEST_ID_VALIDATION_RULE } from "./rules/inbound-request-id-validation.js";
import { INBOUND_REQUEST_ID_VALIDATION_GATE_RULE } from "./rules/inbound-request-id-validation-gate.js";
import { INBOUND_REPLAY_PROTECTION_RECEIVED_AT_VALIDATION_RULE } from "./rules/inbound-replay-protection-received-at-validation.js";
import { INBOUND_REPLAY_PROTECTION_RECEIVED_AT_VALIDATION_GATE_RULE } from "./rules/inbound-replay-protection-received-at-validation-gate.js";
import { INBOUND_AUTHENTICATION_HINT_VALIDATION_RULE } from "./rules/inbound-authentication-hint-validation.js";
import { INBOUND_AUTHENTICATION_HINT_VALIDATION_GATE_RULE } from "./rules/inbound-authentication-hint-validation-gate.js";
import { INBOUND_AUTHENTICATION_METHOD_BINDING_RULE } from "./rules/inbound-authentication-method-binding.js";
import { INBOUND_AUTHENTICATION_METHOD_BINDING_GATE_RULE } from "./rules/inbound-authentication-method-binding-gate.js";
import { INBOUND_AUTHENTICATION_SUBJECT_BINDING_RULE } from "./rules/inbound-authentication-subject-binding.js";
import { INBOUND_AUTHENTICATION_SUBJECT_BINDING_GATE_RULE } from "./rules/inbound-authentication-subject-binding-gate.js";
import { INBOUND_AUTHENTICATION_ISSUER_BINDING_RULE } from "./rules/inbound-authentication-issuer-binding.js";
import { INBOUND_AUTHENTICATION_ISSUER_BINDING_GATE_RULE } from "./rules/inbound-authentication-issuer-binding-gate.js";
import { INBOUND_AUTHENTICATION_METADATA_VALIDATION_RULE } from "./rules/inbound-authentication-metadata-validation.js";
import { INBOUND_AUTHENTICATION_METADATA_VALIDATION_GATE_RULE } from "./rules/inbound-authentication-metadata-validation-gate.js";
import { INBOUND_AUTHENTICATION_EVIDENCE_INSTANT_VALIDATION_RULE } from "./rules/inbound-authentication-evidence-instant-validation.js";
import { INBOUND_AUTHENTICATION_EVIDENCE_INSTANT_VALIDATION_GATE_RULE } from "./rules/inbound-authentication-evidence-instant-validation-gate.js";
import { INBOUND_AUTHENTICATION_ISSUED_AT_VALIDATION_RULE } from "./rules/inbound-authentication-issued-at-validation.js";
import { INBOUND_AUTHENTICATION_ISSUED_AT_VALIDATION_GATE_RULE } from "./rules/inbound-authentication-issued-at-validation-gate.js";
import { PREPARED_INBOUND_RUNTIME_EXECUTION_RULE } from "./rules/prepared-inbound-runtime-execution.js";
import { LOOP_RUNNER_EXECUTE_VALIDATION_REPAIR_RULE } from "./rules/looprunner-execute-validation-repair.js";
import { CONFIGURED_INBOUND_SECURITY_ADAPTER_RULE } from "./rules/configured-inbound-security-adapter.js";
import { CODEX_PROVIDER_CONTROLLED_COMMIT_RULE } from "./rules/codex-provider-controlled-commit.js";
import { AUDIT_GITHUB_ACTIONS_PARALLEL_CI_RULE } from "./rules/github-actions-parallel-ci.js";
import { CORE_CONCRETE_DEPENDENCY_DIRECTION_RULE } from "./rules/core-concrete-dependency-direction.js";
import { CONCRETE_PROVIDER_EXPOSURE_RULE } from "./rules/concrete-provider-exposure.js";
import { CLI_COMMAND_BOUNDARY_RULE } from "./rules/cli-command-boundary.js";
import { COMPOSITION_ROOT_DIRECTION_RULE } from "./rules/composition-root-direction.js";
import { APPLICATION_ASSEMBLY_CONTRACT_RULE } from "./rules/application-assembly-contract.js";
import {
  AUTOMATION_ASSEMBLY_CONTRACTS_RULE,
  AUTOMATION_ASSEMBLY_INERTNESS_RULE,
  AUTOMATION_AUDIT_DOCUMENTATION_RULE,
  AUTOMATION_CONTRACT_PURITY_RULE,
  AUTOMATION_CORE_CONTRACTS_RULE,
  AUTOMATION_DEPENDENCY_DIRECTION_RULE,
  AUTOMATION_FORBIDDEN_DEPENDENCIES_RULE,
  AUTOMATION_FORGE_CONTRACTS_RULE,
  AUTOMATION_POLICY_CONTRACTS_RULE,
  AUTOMATION_PIPELINE_ADMISSION_CONTRACTS_RULE,
  AUTOMATION_PIPELINE_ADMISSION_IDENTIFIERS_RULE,
  AUTOMATION_PIPELINE_ADMISSION_MATRIX_RULE,
  AUTOMATION_PIPELINE_ADMISSION_PURITY_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_CONTRACTS_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_IDENTIFIERS_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_MATRIX_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_PURITY_RULE,
  AUTOMATION_WORKER_COMMAND_CONTRACTS_RULE,
  AUTOMATION_WORKER_COMMAND_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_COMMAND_MATRIX_RULE,
  AUTOMATION_WORKER_COMMAND_PURITY_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_CONTRACTS_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_MATRIX_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_PURITY_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_CONTRACTS_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_MATRIX_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_PURITY_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_CONTRACTS_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_INVARIANTS_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_COMPOSITION_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_INVARIANTS_RULE,
  AUTOMATION_PROVIDER_CONTRACTS_RULE,
} from "./rules/automation-contracts.js";
import { AUTOMATION_CI_CONTRACT_RULE } from "./rules/automation-ci-contract.js";
import { registerAuditRulesForIntegrityCheck } from "./rules/audit.js";
import { AUDIT_RULES as BASE_AUDIT_RULES } from "./rules.js";

const AUTOMATION_AUDIT_RULES = [
  AUTOMATION_CORE_CONTRACTS_RULE,
  AUTOMATION_PROVIDER_CONTRACTS_RULE,
  AUTOMATION_FORGE_CONTRACTS_RULE,
  AUTOMATION_POLICY_CONTRACTS_RULE,
  AUTOMATION_ASSEMBLY_CONTRACTS_RULE,
  AUTOMATION_ASSEMBLY_INERTNESS_RULE,
  AUTOMATION_CONTRACT_PURITY_RULE,
  AUTOMATION_DEPENDENCY_DIRECTION_RULE,
  AUTOMATION_FORBIDDEN_DEPENDENCIES_RULE,
  AUTOMATION_AUDIT_DOCUMENTATION_RULE,
  AUTOMATION_CI_CONTRACT_RULE,
  AUTOMATION_PIPELINE_ADMISSION_CONTRACTS_RULE,
  AUTOMATION_PIPELINE_ADMISSION_PURITY_RULE,
  AUTOMATION_PIPELINE_ADMISSION_MATRIX_RULE,
  AUTOMATION_PIPELINE_ADMISSION_IDENTIFIERS_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_CONTRACTS_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_PURITY_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_MATRIX_RULE,
  AUTOMATION_PIPELINE_WORKER_HANDOFF_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_COMMAND_CONTRACTS_RULE,
  AUTOMATION_WORKER_COMMAND_PURITY_RULE,
  AUTOMATION_WORKER_COMMAND_MATRIX_RULE,
  AUTOMATION_WORKER_COMMAND_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_CONTRACTS_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_PURITY_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_MATRIX_RULE,
  AUTOMATION_WORKER_DISPATCH_PORT_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_CONTRACTS_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_PURITY_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_MATRIX_RULE,
  AUTOMATION_WORKER_DISPATCH_INVOCATION_IDENTIFIERS_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_CONTRACTS_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_MATRIX_RULE,
  AUTOMATION_WORKER_DISPATCH_SERVICE_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_INITIALIZATION_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_INVOCATION_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_COMPOSITION_RULE,
  AUTOMATION_WORKER_EXECUTION_START_SERVICE_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_START_RECEIPT_INVARIANTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_CONTRACTS_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_DEPENDENCIES_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_MATRIX_RULE,
  AUTOMATION_WORKER_EXECUTION_LIFECYCLE_TRANSITION_INVARIANTS_RULE,
] as const;

const RUNTIME_AUDIT_RULES = [
  ...BASE_AUDIT_RULES,
  RUNTIME_EXECUTION_RECEIPT_REPORTING_RULE,
  RUNTIME_EXECUTION_RECEIPT_REPORTING_SERIALIZATION_RULE,
  RUNTIME_EXECUTION_PUBLIC_RESULT_FACADE_RULE,
  RUNTIME_RULE_INVENTORY_NORMALIZATION_RULE,
  RUNTIME_AUDIT_MANIFEST_CONSISTENCY_RULE,
  INBOUND_SECURITY_CONTRACT_RULE,
  INBOUND_SECURITY_GATE_RULE,
  INBOUND_AUTHENTICATION_VERIFICATION_RULE,
  INBOUND_AUTHENTICATION_GATE_RULE,
  INBOUND_REQUEST_HANDLER_NEUTRALITY_RULE,
  INBOUND_REQUEST_HANDLER_GATE_RULE,
  INBOUND_TRANSPORT_ADAPTER_NEUTRALITY_RULE,
  INBOUND_TRANSPORT_ADAPTER_GATE_RULE,
  INBOUND_REPLAY_PROTECTION_NEUTRALITY_RULE,
  INBOUND_REPLAY_PROTECTION_GATE_RULE,
  INBOUND_REPLAY_PROTECTED_AUTHENTICATION_NEUTRALITY_RULE,
  INBOUND_REPLAY_PROTECTED_AUTHENTICATION_GATE_RULE,
  INBOUND_EVALUATION_TIME_COHERENCE_RULE,
  INBOUND_EVALUATION_TIME_COHERENCE_GATE_RULE,
  INBOUND_REPLAY_EVIDENCE_BINDING_RULE,
  INBOUND_REPLAY_EVIDENCE_BINDING_GATE_RULE,
  INBOUND_PRINCIPAL_BINDING_RULE,
  INBOUND_PRINCIPAL_BINDING_GATE_RULE,
  INBOUND_PRINCIPAL_PRESENCE_RULE,
  INBOUND_PRINCIPAL_PRESENCE_GATE_RULE,
  INBOUND_AUTH_EVIDENCE_VALIDITY_RULE,
  INBOUND_AUTH_EVIDENCE_VALIDITY_GATE_RULE,
  INBOUND_TENANT_BINDING_RULE,
  INBOUND_TENANT_BINDING_GATE_RULE,
  INBOUND_OPERATION_BINDING_RULE,
  INBOUND_OPERATION_BINDING_GATE_RULE,
  INBOUND_OPERATION_POLICY_ADMISSION_RULE,
  INBOUND_OPERATION_POLICY_ADMISSION_GATE_RULE,
  INBOUND_REPLAY_REQUEST_BINDING_RULE,
  INBOUND_REPLAY_REQUEST_BINDING_GATE_RULE,
  INBOUND_REPLAY_STATE_REJECTION_RULE,
  INBOUND_REPLAY_STATE_REJECTION_GATE_RULE,
  INBOUND_PROJECT_BINDING_RULE,
  INBOUND_PROJECT_BINDING_GATE_RULE,
  INBOUND_REPLAY_RECEIPT_TIME_VALIDATION_RULE,
  INBOUND_REPLAY_RECEIPT_TIME_VALIDATION_GATE_RULE,
  INBOUND_REPLAY_PORT_RECEIPT_TIME_VALIDATION_RULE,
  INBOUND_REPLAY_PORT_RECEIPT_TIME_VALIDATION_GATE_RULE,
  INBOUND_VERIFICATION_REQUEST_BINDING_RULE,
  INBOUND_VERIFICATION_REQUEST_BINDING_GATE_RULE,
  INBOUND_VERIFICATION_EVALUATION_TIME_BINDING_RULE,
  INBOUND_VERIFICATION_EVALUATION_TIME_BINDING_GATE_RULE,
  INBOUND_REPLAY_NONCE_VALIDATION_RULE,
  INBOUND_REPLAY_NONCE_VALIDATION_GATE_RULE,
  INBOUND_AUTHENTICATION_EVIDENCE_WINDOW_VALIDATION_RULE,
  INBOUND_AUTHENTICATION_EVIDENCE_WINDOW_VALIDATION_GATE_RULE,
  INBOUND_REPLAY_RECEIVED_AT_VALIDATION_RULE,
  INBOUND_REPLAY_RECEIVED_AT_VALIDATION_GATE_RULE,
  INBOUND_EVALUATION_TIME_VALIDATION_RULE,
  INBOUND_EVALUATION_TIME_VALIDATION_GATE_RULE,
  INBOUND_REQUEST_ID_VALIDATION_RULE,
  INBOUND_REQUEST_ID_VALIDATION_GATE_RULE,
  INBOUND_REPLAY_PROTECTION_RECEIVED_AT_VALIDATION_RULE,
  INBOUND_REPLAY_PROTECTION_RECEIVED_AT_VALIDATION_GATE_RULE,
  INBOUND_AUTHENTICATION_HINT_VALIDATION_RULE,
  INBOUND_AUTHENTICATION_HINT_VALIDATION_GATE_RULE,
  INBOUND_AUTHENTICATION_METHOD_BINDING_RULE,
  INBOUND_AUTHENTICATION_METHOD_BINDING_GATE_RULE,
  INBOUND_AUTHENTICATION_SUBJECT_BINDING_RULE,
  INBOUND_AUTHENTICATION_SUBJECT_BINDING_GATE_RULE,
  INBOUND_AUTHENTICATION_ISSUER_BINDING_RULE,
  INBOUND_AUTHENTICATION_ISSUER_BINDING_GATE_RULE,
  INBOUND_AUTHENTICATION_METADATA_VALIDATION_RULE,
  INBOUND_AUTHENTICATION_METADATA_VALIDATION_GATE_RULE,
  INBOUND_AUTHENTICATION_EVIDENCE_INSTANT_VALIDATION_RULE,
  INBOUND_AUTHENTICATION_EVIDENCE_INSTANT_VALIDATION_GATE_RULE,
  INBOUND_AUTHENTICATION_ISSUED_AT_VALIDATION_RULE,
  INBOUND_AUTHENTICATION_ISSUED_AT_VALIDATION_GATE_RULE,
  PREPARED_INBOUND_RUNTIME_EXECUTION_RULE,
  LOOP_RUNNER_EXECUTE_VALIDATION_REPAIR_RULE,
  CONFIGURED_INBOUND_SECURITY_ADAPTER_RULE,
  CODEX_PROVIDER_CONTROLLED_COMMIT_RULE,
  CORE_CONCRETE_DEPENDENCY_DIRECTION_RULE,
  CONCRETE_PROVIDER_EXPOSURE_RULE,
  CLI_COMMAND_BOUNDARY_RULE,
  COMPOSITION_ROOT_DIRECTION_RULE,
  APPLICATION_ASSEMBLY_CONTRACT_RULE,
] as const;

export const AUDIT_RULES = createAuditRuleRegistry(
  [...RUNTIME_AUDIT_RULES, ...AUTOMATION_AUDIT_RULES].map((rule) =>
    rule.id === "AUDIT-012" ? AUDIT_GITHUB_ACTIONS_PARALLEL_CI_RULE : rule,
  ),
);

registerAuditRulesForIntegrityCheck(AUDIT_RULES);
registerRuntimeAuditManifestInventory(AUDIT_RULES);
