import assert from "node:assert/strict";
import { test } from "node:test";
import { ExecutionDecisionProviderFailure } from "../../src/governance/execution-decision-provider.js";
import { ExecutionDecisionCliBoundaryFailure } from "../../src/gui/desktop/execution-decision-cli-proposer.js";
import { createDesktopExecutionDecisionController } from "../../src/gui/desktop/execution-decision-controller.js";
import { ExecutionDecisionDraftValidationFailure } from "../../src/governance/execution-decision-errors.js";
import { ExecutionDecisionCurrentCliFailure } from "../../src/gui/desktop/execution-decision-cli-current.js";

function controller(error: unknown) { return createDesktopExecutionDecisionController({ keychainReader: { read: async () => ({ ok: false, reason: "unavailable" }) }, cliInvoker: { invoke: async () => ({ ok: false, kind: "spawn-error", raw: "unused" }) }, resolveRepositoryPath: () => "/loop", service: { prepare: async () => { throw error; }, approve: async () => ({ ok: false as const, code: "decision_draft_missing" }) } }); }
test("controller never presents an unknown preparation error as provider_unavailable", async () => { const result = await controller(new Error("boom")).prepare("lp-infra"); assert.equal(result.ok, false); if (!result.ok) { assert.equal(result.code, "execution_decision_internal_error"); assert.doesNotMatch(result.message, /Anthropic/); } });
test("controller preserves typed CLI and provider failures", async () => { const cli = await controller(new ExecutionDecisionCliBoundaryFailure("cli_timeout")).prepare("lp-infra"); assert.equal(cli.ok, false); if (!cli.ok) assert.equal(cli.code, "cli_timeout"); const provider = await controller(new ExecutionDecisionProviderFailure({ status: "failed", provider: "anthropic_api", model: "claude-sonnet-5", code: "provider_unavailable", message: "private", durationMs: 1, truncated: false })).prepare("lp-infra"); assert.equal(provider.ok, false); if (!provider.ok) assert.equal(provider.code, "provider_unavailable"); });
test("controller gives a bounded local message and telemetry for a rejected provider draft", async () => { const result = await controller(new ExecutionDecisionDraftValidationFailure("allowed_paths_invalid", { model: "claude-sonnet-5", durationMs: 6041, usage: { inputTokens: 671, outputTokens: 369 }, actualCalculatedCostUsd: 0.005032 })).prepare("lp-infra"); assert.equal(result.ok, false); if (!result.ok) { assert.equal(result.code, "decision_draft_invalid"); assert.equal(result.message, "Le périmètre de fichiers proposé est invalide."); assert.deepEqual(result.provider, { model: "claude-sonnet-5", durationMs: 6041, usage: { inputTokens: 671, outputTokens: 369 }, actualCalculatedCostUsd: 0.005032, draftValidationIssue: "allowed_paths_invalid" }); } });
test("controller maps typed current approval failures and never relabels unknown approval failures as recovery",async()=>{const typed=createDesktopExecutionDecisionController({keychainReader:{read:async()=>({ok:false,reason:"unavailable"})},cliInvoker:{invoke:async()=>({ok:false,kind:"spawn-error",raw:"unused"})},resolveRepositoryPath:()=>"/loop",service:{prepare:async()=>({ok:false as const,code:"decision_draft_missing"}),approve:async()=>{throw new ExecutionDecisionCurrentCliFailure("execution_decision_current_timeout");}}});const typedResult=await typed.approve("draft");assert.equal(typedResult.ok,false);if(!typedResult.ok)assert.equal(typedResult.code,"execution_decision_current_timeout");const unknown=createDesktopExecutionDecisionController({keychainReader:{read:async()=>({ok:false,reason:"unavailable"})},cliInvoker:{invoke:async()=>({ok:false,kind:"spawn-error",raw:"unused"})},resolveRepositoryPath:()=>"/loop",service:{prepare:async()=>({ok:false as const,code:"decision_draft_missing"}),approve:async()=>{throw Error("private");}}});const unknownResult=await unknown.approve("draft");assert.equal(unknownResult.ok,false);if(!unknownResult.ok){assert.equal(unknownResult.code,"execution_decision_approval_internal_error");assert.notEqual(unknownResult.code,"decision_draft_recovery_failed");}});
test("controller exposes bounded publication messages",async()=>{for(const [code,message] of [["decision_draft_serialize_failed","sérialisée"],["decision_draft_read_previous_failed","lue avant remplacement"],["decision_draft_write_temp_failed","temporaire"],["decision_draft_rename_failed","remplacer"]] as const){const value=createDesktopExecutionDecisionController({keychainReader:{read:async()=>({ok:false,reason:"unavailable"})},cliInvoker:{invoke:async()=>({ok:false,kind:"spawn-error",raw:"unused"})},resolveRepositoryPath:()=>"/loop",service:{prepare:async()=>({ok:false as const,code:"decision_draft_missing"}),approve:async()=>({ok:false as const,code})}});const result=await value.approve("draft");assert.equal(result.ok,false);if(!result.ok)assert.match(result.message,new RegExp(message));}});
