import assert from "node:assert/strict";
import { describe, test } from "node:test";
import { evaluateBridgeContract } from "../../src/core/bridge-contract.js";
const subject = { authorityId: "a", authorityVersion: "v1", approvalId: "p", approvalVersion: "v1", verificationId: "v", verificationVersion: "v1", lifecycleId: "l", lifecycleVersion: "v1", lifecycleState: "active" as const, descriptorId: "d", descriptorVersion: "v1", handoffId: "h", handoffVersion: "v1", providerId: "provider", protocolId: "protocol", mappingId: "mapping", intentId: "intent", runtimeCapabilityId: "runtime", transportCapabilityId: "transport", policyId: "policy" };
const context = { supportedKinds: ["declarative_handoff"], expectedPolicyId: "policy" };
describe("bridge contract RFC", () => {
 test("is immutable, serializable, eligible and never executable", () => { const result = evaluateBridgeContract({ kind: "declarative_handoff", subject, evaluationAt: "2026-07-19T00:00:00.000Z", evidenceReferences: ["b", "a"] }, context); assert.equal(result.bridgeEligible, true); assert.equal(result.executionAllowed, false); assert.equal(result.executionStarted, false); assert.equal(Object.isFrozen(result), true); assert.equal(JSON.parse(JSON.stringify(result)).executionAllowed, false); assert.deepEqual(result.contract.evidence.map((item) => item.id), ["a", "b"]); });
 test("fails closed for missing input, references, inactive lifecycle, time and unsupported kind", () => { assert.equal(evaluateBridgeContract(null, context).bridgeEligible, false); assert.equal(evaluateBridgeContract({ kind: "declarative_handoff", subject: { ...subject, authorityId: "" }, evaluationAt: "x", evidenceReferences: ["a"] }, context).bridgeEligible, false); assert.equal(evaluateBridgeContract({ kind: "declarative_handoff", subject: { ...subject, lifecycleState: "expired" }, evaluationAt: "x", evidenceReferences: ["a"] }, context).bridgeEligible, false); assert.equal(evaluateBridgeContract({ kind: "declarative_handoff", subject, evaluationAt: "", evidenceReferences: ["a"] }, context).bridgeEligible, false); assert.equal(evaluateBridgeContract({ kind: "other" as "declarative_handoff", subject, evaluationAt: "x", evidenceReferences: ["a"] }, context).bridgeEligible, false); });
});
