import assert from "node:assert/strict";
import { test } from "node:test";
import { createExecutionDecisionProposalProvider, EXECUTION_DECISION_PROPOSAL_SCHEMA } from "../../src/governance/execution-decision-provider.js";
import { createExecutionDecisionDraft } from "../../src/governance/execution-decision-draft.js";
import type { TextOnlyProvider, TextOnlyProviderInput } from "../../src/text-only-provider/index.js";

const sha = "a".repeat(40);
const current = { project: "fixture", projectPath: "/private/project", candidateId: "H4-L1", gitHead: sha, sourceDocument: "roadmap.md", executionDecisionPath: ".governance/decision.yaml" } as const;
function fixtureProvider(output: string, calls: TextOnlyProviderInput[]): TextOnlyProvider { return { async invoke(input) { calls.push(input); return { status: "completed", provider: "test", model: input.model, output, durationMs: 1, truncated: false }; } }; }
function dependencies(candidate = { id: "H4-L1", text: "Write ADR", path: "roadmap.md", status: "todo" }) { return { loadConfig: () => ({ projects: [{ name: "fixture", type: "infra", path: "/private/project" }] }), findProject: (config: { projects: readonly unknown[] }) => config.projects[0] as never, report: () => ({ objective: { content: "Canonical objective" }, planning: { mode: "plan" }, roadmap: { selectedCandidate: candidate, summary: "one safe candidate" } }) as never }; }
test("builds a bounded canonical context and invokes balanced Anthropic profile once", async () => { const calls: TextOnlyProviderInput[] = []; const propose = createExecutionDecisionProposalProvider(fixtureProvider(JSON.stringify({ objective: "ADR", deliverables: ["doc"], outOfScope: ["run"], allowedPaths: ["ADR/x.md"] }), calls), dependencies()); const result = await propose(current); assert.equal(calls.length, 1); assert.equal(calls[0]?.model, "claude-sonnet-5"); assert.equal(calls[0]?.effort, "low"); assert.equal(calls[0]?.timeoutMs, 60_000); assert.equal(calls[0]?.outputSchema?.schema, EXECUTION_DECISION_PROPOSAL_SCHEMA); const context = calls[0] ? calls[0].contextJson : ""; const prompt = calls[0]?.systemPrompt ?? ""; assert.match(prompt, /exact repository-relative POSIX file paths/); assert.match(prompt, /paths ending with \//); assert.match(context, /Canonical objective/); assert.match(context, /Write ADR/); assert.match(context, /roadmap\.md/); assert.doesNotMatch(context, /private\/project|gitHead|ANTHROPIC_API_KEY/); assert.deepEqual(result.allowedPaths, ["ADR/x.md"]); });
test("fails closed before provider invocation when selected candidate diverges", async () => { const calls: TextOnlyProviderInput[] = []; const propose = createExecutionDecisionProposalProvider(fixtureProvider("{}", calls), dependencies({ id: "other", text: "other", path: "roadmap.md", status: "todo" })); await assert.rejects(() => propose(current)); assert.equal(calls.length, 0); });
for (const output of ["not json", JSON.stringify({ objective: "x", deliverables: ["x"], outOfScope: ["x"], allowedPaths: ["x"], state: "READY" }), JSON.stringify({ objective: "x", deliverables: [1], outOfScope: ["x"], allowedPaths: ["x"] })]) test("rejects invalid or unauthorized provider output", async () => { const calls: TextOnlyProviderInput[] = []; const propose = createExecutionDecisionProposalProvider(fixtureProvider(output, calls), dependencies()); await assert.rejects(() => propose(current)); assert.equal(calls.length, 1); });
test("dangerous provider path remains rejected by B1 draft validation", async () => { const result = createExecutionDecisionDraft(current, { objective: "x", deliverables: ["x"], outOfScope: ["x"], allowedPaths: [".git/config"] }); assert.equal(result.ok, false); });
