import assert from "node:assert/strict";
import { test } from "node:test";
import { parseExecutionDecisionFile } from "../../src/governance/execution-decision.js";
import { createExecutionDecisionDraftStore, prepareStoredExecutionDecisionDraft, serializeReadyExecutionDecision } from "../../src/governance/execution-decision-approval.js";
const local = { project: "lp", projectPath: "/tmp/lp", candidateId: "H4-L1", sourceDocument: "roadmap.md", gitHead: "a".repeat(40), executionDecisionPath: ".governance/execution-decision.yaml" }; const provider = { objective: "ADR", deliverables: ["doc"], outOfScope: ["exec"], allowedPaths: ["ADR/1.md"] };
test("stores an opaque draft without writing", () => { const store = createExecutionDecisionDraftStore(); const result = prepareStoredExecutionDecisionDraft(local, provider, store); assert.equal(result.ok, true); if (result.ok) { assert.equal(store.get(result.draftId)?.draft.candidateId, "H4-L1"); assert.doesNotMatch(result.draftId, /lp|H4|draft-1/); assert.equal(store.get("renderer-choice"), null); } });
test("replaces and consumes drafts per project", () => { const store = createExecutionDecisionDraftStore(); const first = prepareStoredExecutionDecisionDraft(local, provider, store); const second = prepareStoredExecutionDecisionDraft(local, provider, store); assert.equal(first.ok && second.ok, true); if (first.ok && second.ok) { assert.equal(store.get(first.draftId), null); store.consume(second.draftId); assert.equal(store.get(second.draftId), null); } });
test("serializes a locally READY V1 decision", () => { const store = createExecutionDecisionDraftStore(); const result = prepareStoredExecutionDecisionDraft(local, provider, store); assert.equal(result.ok, true); if (result.ok) { const parsed = parseExecutionDecisionFile(serializeReadyExecutionDecision(result.draft)); assert.equal(parsed.ok, true); if (parsed.ok) assert.equal(parsed.decision.decision.state, "READY"); } });
test("serializes the observed LP-INFRA H4-L1 draft", () => { const draft = { project: "lp-infra", candidateId: "H4-L1", sourceDocument: "docs/roadmap/projet-lp-infra.md", gitHead: "3b1767c897e53f38b6e8881116b8862cedf38503", objective: "Définir l’architecture du cockpit.", deliverables: ["ADR avec décisions d’architecture"], outOfScope: ["Aucune exécution ni modification d’infrastructure."], allowedPaths: ["ADR/0007-architecture-cockpit.md", "docs/roadmap/projet-lp-infra.md"] } as const; const parsed = parseExecutionDecisionFile(serializeReadyExecutionDecision(draft)); assert.equal(parsed.ok, true); if (parsed.ok) { assert.equal(parsed.decision.decision.state, "READY"); assert.equal(parsed.decision.decision.candidate.id, "H4-L1"); assert.equal(parsed.decision.source.gitHead, draft.gitHead); assert.deepEqual(parsed.decision.decision.candidate.allowedPaths, draft.allowedPaths); } });
